name: Deploy

on:
  push:
    branches:
      - develop

env:
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/test-image:${{ github.sha }}
  SERVICE_NAME: fika-bff-nakagome
  PORT: 8080
  GCP_REGION: us-central1
  ACCESS_TOKEN_PRIVATE_REPO: ${{ secrets.ACCESS_TOKEN_PRIVATE_REPO }}
  USER_NAME: githubmn324

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: "Checkout the repository"
        uses: actions/checkout@v2

      # GCP 認証
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # gcloud コマンドの設定
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      # Docker に gcloud コマンドの Credential を使わせる
      - name: "Configure docker to use the gcloud cli"
        run: gcloud auth configure-docker --quiet

      # # Docker に .netrc の設定をする
      # - name: Create .nettrc setting file
      #   uses: little-core-labs/netrc-creds@master
      #   with:
      #     machine: github.com
      #     login: $USER_NAME
      #     password: $ACCESS_TOKEN_PRIVATE_REPO

      - name: Generate Github App token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GIT_HUB_APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      # Docker イメージを作成
      - name: "Build a docker image"
        run: docker build -t $IMAGE . --no-cache --build-arg TOKEN=${{ steps.generate_token.outputs.token }}
        # run: docker build -t $IMAGE . --build-arg ACCESS_TOKEN_PRIVATE_REPO=$ACCESS_TOKEN_PRIVATE_REPO
        # run: docker build -t $IMAGE . --build-arg ACCESS_TOKEN_PRIVATE_REPO=$ACCESS_TOKEN_PRIVATE_REPO --build-arg USER_NAME=$USER_NAME

      # Docker イメージを Container Registry に Push
      - name: "Push the docker image to Container Registry"
        run: docker push $IMAGE

      # Container Registry から Cloud Run へデプロイ
      - name: "Deploy to Cloud Run"
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --port $PORT \
            --project $GCP_PROJECT_ID \
            --region $GCP_REGION \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
